### ISSUE TITLE
Module Not Found Error: No module named 'src'

### ISSUE THREAD

**Issue by tahavarol** [nyukat/breast_cancer_classifier#4]
Hi, when i try to execute the run.sh I got the following error. Can you help me please? Thanks :)

Stage 1: Crop Mammograms
Traceback (most recent call last):
  File "src/cropping/crop_mammogram.py", line 32, in <module>
    import src.utilities.pickling as pickling
ModuleNotFoundError: No module named 'src'
Stage 2: Extract Centers
Traceback (most recent call last):
  File "src/optimal_centers/get_optimal_centers.py", line 32, in <module>
    from src.constants import INPUT_SIZE_DICT
ModuleNotFoundError: No module named 'src'
Stage 3: Generate Heatmaps
Traceback (most recent call last):
  File "src/heatmaps/run_producer.py", line 36, in <module>
    import src.heatmaps.models as models
ModuleNotFoundError: No module named 'src'
Stage 4a: Run Classifier (Image)
Traceback (most recent call last):
  File "src/modeling/run_model.py", line 34, in <module>
    import src.utilities.pickling as pickling
ModuleNotFoundError: No module named 'src'
Stage 4b: Run Classifier (Image+Heatmaps)
Traceback (most recent call last):
  File "src/modeling/run_model.py", line 34, in <module>
    import src.utilities.pickling as pickling
ModuleNotFoundError: No module named 'src'

**Comment by jpatrickpark** [comment]
Hi,

One potential reason is that you might not be running run.sh in `breast_cancer_classifier` directory. Line 11 of `run.sh`: `PYTHONPATH=$(pwd):$PYTHONPATH` is written assuming that `pwd` will return /PATH/TO/breast_cancer_classifier.  If this is the issue, you can either run it inside `breast_cancer_classifier` directory or run this following line beforehand (or add the following line in your ~/.bashrc) so that you can run it anywhere (modify it to be your path to this clone).

`export PYTHONPATH=/PATH/TO/breast_cancer_classifier:$PYTHONPATH`

If the above fails, you can manually add the following at the beginning of each of python file as a last resort.
```python
import sys
sys.path.append('/PATH/TO/breast_cancer_classifier')
```

**Comment by achiodza** [comment]
Tried that and it worked and now l have this issue

Traceback (most recent call last):
  File "src/modeling/run_model.py", line 192, in <module>
    main()
  File "src/modeling/run_model.py", line 187, in main
    parameters=parameters,
  File "src/modeling/run_model.py", line 145, in load_run_save
    predictions = run_model(model, exam_list, parameters)
  File "src/modeling/run_model.py", line 50, in run_model
    model = model.to(device)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/usr/local/lib/python3.5/dist-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.5/dist-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
